// Generated by TypedCoffeeScript 0.12.2
var compile, Context, CSContext, parse;
cache$ = require('typed-coffee-script');
parse = cache$.parse;
compile = cache$.compile;
Context = require('../vender/esrefactor').Context;
exports.Context = CSContext = function () {
  function CSContext(code) {
    this.context = new Context;
    if (null != code)
      this.setCode(code);
  }
  CSContext.prototype.setCode = function (code) {
    var csAst, jsAst;
    csAst = parse(code, { raw: true });
    jsAst = compile(csAst, { bare: true });
    return this.context.setCode(jsAst);
  };
  CSContext.prototype.identify = function (pos) {
    return this.context.identify(pos);
  };
  return CSContext;
}();